# Site settings
title: Programming/Math
email: naoyoshi0511@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  algorithm, programming, scientific computing
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://na-o-ys.github.io" # the base hostname & protocol for your site
twitter_username: na_o_ys
github_username: na-o-ys

# Build settings
#markdown: redcarpet
markdown: kramdown
redcarpet:
  extensions: [autolink]

highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  #syntax_highlighter_opts:
  #  css_class: hoge

exclude: [vendor]

# Outputting
permalink: /:categories/:year-:month-:day-:title.html

category_map:
  others: その他
  competitions: 競技プログラミング
